/**
 * @name MinecraftDiscord
 * @description Adds a bow sound when receiving messages, block sounds when clicking, and Minecraft-style achievement signs.
 * @author Vos
 * @version 1.1.0
 */

const fs = require("fs");
const path = require("path");

const PLUGIN = "MinecraftDiscord";
const FONT_B64 = "AAEAAAAOAIAAAwBgRkZUTWI2NrkAADh8AAAAHEdERUYADwAeAAA4XAAAAB5PUy8yhflyFgAAAWgAAABWY21hcNRX7YMAAAN4AAABWmN2dCAAIgKIAAAE1AAAAARnYXNw//8AAwAAOFQAAAAIZ2x5ZlYKFdYAAAW4AAAvwGhlYWQGHfgtAAAA7AAAADZoaGVhBt4DbwAAASQAAAAkaG10ePHLAqIAAAHAAAABuGxvY2GD+HfiAAAE2AAAAN5tYXhwAMcAwwAAAUgAAAAgbmFtZSkM6QIAADV4AAAByHBvc3TXzlJDAAA3QAAAARMAAQAAAAEAAB7qAvVfDzz1AAsEAAAAAADRv1qYAAAAANG/WpgAAP8AA4ADAAAAAAgAAgAAAAAAAAABAAADAP8AAFwEAAAAAAADgAABAAAAAAAAAAAAAAAAAAAAbgABAAAAbgCSABcAAAAAAAIAAAABAAEAAABAAC4AAAAAAAEB9AH0AAUAAAKZAswAAACPApkCzAAAAesAMwEJAAACAAYDAAAAAAAAAAAAAwABAAIAAAAAAAAAADJ0dGYAQAAgMAADAP8AAFwDAAEAAAAAAQAAAAAAAAF2ACIAAAAAAVUAAAFAAAAAwAAAAkAAAALAAAACQAAAA4AAQALAAAAAwAAAAcAAAAHAAAABwAAAAoAAQADAAAABgAAAAMAAAAJAAAACQAAAAcAAAAJAAAACQAAAAoAAAALAAAACgAAAAkAAAAJAAAACQAAAAQAAQAEAAEABwAAAAkAAAAHAAAACQAAAA8AAAAKAAAACwAAAAwAAAALAAAACwAAAAoAAAAMAAAACwAAAAYAAQAIAAAACgAAAAoAAAALAAAACwAAAA0AAAALAAAADQAAAA0AAAAKAAAACwAAAAsAAQALAAAACwAAAAsAAAALAAAACwAAAAUAAAAJAAAABQAAAAkAAAAKAAAABQABAAoAAAALAAAACgAAAAkAAAAJAAAACQAAAAkAAAAJAAAAAwAAAAgAAAAJAAAAAwAAAA8AAAAKAAAACQAAAAoAAAAJAAAACAAAAAgAAAAGAAAACQAAAAsAAAAMAAAACwAAAAkAAAAJAAAABgAAAAMAAAAGAAAACwAAAAUAAAAGAAEACQAAAAkAAAAKAAAACgAAAAQAAQAJAAEABgAAAA0AAAAKAAAAEAAAAAAAAAwAAAAMAAAAcAAEAAAAAAFQAAwABAAAAHAAEADgAAAAKAAgAAgACAH4AqSCsMAD//wAAACAAoCCsMAD////j/8LfwNBtAAEAAAAAAAAAAAAAAAABBgAAAQAAAAAAAAABAgAAAAIAAAAAAAAAAAAAAAAAAAABAAADBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyAhIiMkJSYnKCkqKywtLi8wMTIzNDU2Nzg5Ojs8PT4/QEFCQ0RFRkdISUpLTE1OT1BRUlNUVVZXWFlaW1xdXl9gYQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZGVpAAAAAGsAAGoAAAAAAAAAZwAAAAAAAAAAAAAAAGMAAAAAAAAAAGIAAAAAAAAAAAAAAAAAAAAAbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACICiAAAACoAKgAqACoASgB8AMoBFAGSAfICBAI0AmACjgKyAsgC3ALsAyADagOSA+AEMARuBLgFAAU0BYgFygXkBgQGNgZeBo4G0AdEB4AHxggKCEIIeAiiCOoJHglCCW4JtgnaChwKXgqkCtgLJAtyC7gL3gwUDFQMmAz4DTQNfA2iDdwOAg42DkwOZA6iDuIPIg9WD5IPvhAGED4QXhCSENgQ8hE4EWQRnBHcEhgSPhJ8EqYS1BMKE0ATnBPWFBIUSBRmFJoUwhTCFOgVRhWIFeIWOhZeFtQW7heQF+AX4AAAAAIAIgAAATICqgADAAcALrEBAC88sgcEAO0ysQYF3DyyAwIA7TIAsQMALzyyBQQA7TKyBwYB/DyyAQIA7TIzESERJzMRIyIBEO7MzAKq/VYiAmYAAAIAAAAAAIADAAAHAB0AADMjPQE7AR0BJyM9CDsBHQhAQEBAQEBAQEBAQEDAQEBAQEBAQEBAQEBAQEBAQEBAAAAEAAABgAIAAwAABwAPABsAJwAAASM9ATsBHQEhIz0BOwEdASU9AzsBHQMrAz0DOwEdAgFAQEBA/sBAQEABAEBAQMBAQEBAAYBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEAAAAAAAgAAAAACgAMAAD8ARwAAISM9AisBHQIrAT0CKwE9ATsBPQErAT0BOwE9AjsBHQI7AT0COwEdAjsBHQErAR0BOwEdASsBHQIDMz0BKwEdAQHAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAwEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAFAQEBAQAAABAAA/4ACAAMAABsAIwArAD8AAAUjPQErAz0BOwM9ATsBHQE7AR0BKwEdAQMrAT0BOwEVJysBPQE7ARUlKwQ9ATsBPQE7AR0BOwEdAQFAQEBAQEBAQEBAQEBAQEBAgEBAQECAQEBAQAFAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAAYBAQEBAQEBAQEBAQEBAQEBAABAAQAAAA0ADAAADAAkAEwAdACMAJwAtADMANwA9AEMATQBXAFsAYQBnAAAzNTMVJTMVKwE1Mz0DMx0DKwE9AzMdAgU9ATMdAT0BMxU9AjMdASUrATU7ASE1MxUlMxUrATUhPQEzHQEhPQMzHQMrAT0DMx0CJTUzFT0CMx0BJSsBNTsBwEABwEBAQIBAwEBA/oBAQEABQEBAQED+wED+wEBAQAGAQP7AQMBAQAHAQED+QEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAgAAAAAAoADAAAHABMAHwArADMAQwBLAFMAACEjPQE7AR0BISsCPQE7Ax0BNysBPQM7AR0CBSsBPQM7AR0CJT0BOwEdASsFPQM7AR0BOwEVNysBPQE7ARUnKwE9ATsBFQJAQEBA/sBAQEBAQEBAgEBAQED+gEBAQEABgEBAQMBAQEBAQEBAQIBAQEBAgEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEDAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAEAAAIAAIADAAALAAATIz0DOwEdA0BAQEACAEBAQEBAQEBAAAMAAAAAAYADAAALAB8AKwAAISsCPQE7Ax0BJSsBPQc7AR0GEysCPQE7Ax0BAUBAQEBAQEBA/wBAQEBAwEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQAHAQEBAQAAAAAMAAAAAAYADAAALAB8AKwAAMysCPQE7Ax0BPQg7AR0HIwMrAz0BOwMVwEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEACAEBAQAABAAABgAGAAwAAIwAAASM9ASsBHQErAT0BMz0BIz0BOwEdATsBPQE7AR0BIx0BMx0BAUBAQEBAQEBAQEBAQEBAQEABgEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAAAEAQACAAkACgAAfAAAlIz0CKwI9ATsCPQI7AR0COwIdASsCHQIBQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAAAIAAP+AAIAAgAADAA0AABU1MxU9ASM9ATsBHQJAQEBAgEBAQEBAQEBAQAAAAQAAAMABQAFAAA0AACUrAz0BOwQdAQEAQEBAQEBAQEBAwEBAQEAAAAEAAAAAAIAAgAAHAAAzIz0BOwEdAUBAQEBAQEBAAAAACAAAAAACAAMAAAMACQANABMAFwAdACEAJwAAMTUzFT0CMx0BPQEzFT0CMx0BPQEzFT0CMx0BPQEzFT0CMx0BQEBAQEBAQEBAQEBAQEBAgEBAQEBAQECAQEBAQEBAQIBAQEBAQEBAAAADAAAAAAIAAwAACwA/AEsAACErAj0BOwMdAT0FIx0BKwEdASMVKwE9BzsBHQQzPQE7AT0BMzU7AR0HIwMrAz0BOwMVAUBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEACAEBAQAAAAQAAAAABgAMAACcAACErBD0BOwE9BSsBPQE7AT0BOwEdCTsBHQEBQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAGAAAAAAIAAwAAFwAfACcALwA3AEMAACErBj0DOwEdATsFHQEBPQE7AR0BIzc9ATsBHQEjNz0BOwEdASMhIz0BOwEdASUrAz0BOwMVAcBAQEBAQEBAQEBAQEBAQED+gEBAQEBAQEBAQEBA/oBAQEABAEBAQEBAQEBAQEBAQEBAQEABAEBAQECAQEBAQIBAQEBAQEBAQIBAQEAAAAAHAAAAAAIAAwAACwAVAB0AJQAvADcAQwAAISsCPQE7Ax0BPQM7AR0CIyErAT0BOwEVJSsBPQE7ARU9AzsBHQIjJSM9ATsBHQElKwM9ATsDFQFAQEBAQEBAQEBAQP7AQEBAQAEAQEBAQEBAQP6AQEBAAQBAQEBAQEBAQEBAQECAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQIBAQEAAAAAAAgAAAAACQAMAACkAOQAAISM9ASsFPQM7AT0BOwE9ATsBPQE7AR0HMx0BIx0BAzM9AysBHQErAR0BOwEBwEBAQEBAQEBAQEBAQEBAQEBAwEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEABAEBAQEBAQEBAAAAAAAUAAAAAAoADAAARABkAHwAvAEsAACErBT0BOwYdAT0COwEdASMhIz0BMxUlKwU9ATsFFSUrAT0FOwcdASsFHQIBwEBAQEBAQEBAQEBAQEBAQED+AEBAAcBAQEBAQEBAQEBAQED+gEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAFAAAAAAJAAwAADQAVAC8ANwBDAAAhKwM9ATsEHQE9AjsBHQEjISsBPQU7AR0BOwQdASsEFRE9ATsBHQEjJSsCPQE7Ax0BAYBAQEBAQEBAQEBAQED+gEBAQEBAQEBAQEBAQEBAQEBAAQBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEABQEBAQECAQEBAQAADAAAAAAIAAwAADwAXADMAADMjPQU7AR0FET0BOwEdASM3PQErAx0BKwE9AzsHHQMjwEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEABgEBAQECAQEBAQEBAQEBAQEBAAAcAAAAAAgADAAALABUAHwArADUAPwBLAAAhKwI9ATsDHQE9AzsBHQIjISsBPQI7AR0BJSsDPQE7AxU9AzsBHQIjISsBPQI7AR0BJSsDPQE7AxUBQEBAQEBAQEBAQED+wEBAQEABAEBAQEBAQEBAQEBA/sBAQEBAAQBAQEBAQEBAQEBAQECAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAgEBAQAAAAAQAAAAAAgADAAALACcAMwA/AAAhKwI9ATsDHQE9AisDPQE7Az0DOwEdByMBKwE9AzsBHQIlKwM9ATsDFQFAQEBAQEBAQEBAQEBAQEBAQEBA/sBAQEBAAQBAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQAEAQEBAQEBAQMBAQEAAAAIAQAAAAMACQAAHAA8AADMjPQE7AR0BAyM9ATsBHQGAQEBAQEBAQEBAQEABwEBAQEAAAAADAED/gADAAkAAAwANABUAABc1MxU9ASM9ATsBHQIDIz0BOwEdAUBAQEBAQEBAQIBAQEBAQEBAQEACAEBAQEAABQAAAIABgAKAAAcADQAVABsAIwAAJSM9ATsBHQEnKwE1OwErAj0BOwEVNzMVKwE1Mz0BOwEdASMBQEBAQIBAQEBAgEBAQEBAQEBAgEBAQIBAQEBAgEBAQECAQEBAQEBAAAAAAAIAAADAAgACQAATACcAACUrBj0BOwcdAQMrBj0BOwcdAQHAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQMBAQEBAAQBAQEBAAAAABQAAAIABgAKAAAcADQAVABsAIwAANyM9ATsBHQE3MxUrATUzPQE7AR0BIycrATU7ASsCPQE7ARVAQEBAQEBAQIBAQEBAQEBAQIBAQEBAgEBAQEDAQEBAQEBAgEBAQEAABgAAAAACAAMAAAcADwAXACEAKQA1AAAzIz0BOwEdAScjPQE7AR0BPQI7AR0BIzc9AjsBHQIjJSM9ATsBHQElKwM9ATsDFcBAQEBAQEBAQEBAQEBAQP6AQEBAAQBAQEBAQEBAQEBAQEDAQEBAQIBAQEBAgEBAQEBAQEBAQEBAgEBAQAAAAgAA/0ADgAMAAIMAkQAABSsINSM1Iz0KMzUzNTsJFTMVMx0IKwEVKwc9BTsBPQE7BB0FMz0HKwkdCjsJNTsBFSMVIxUBMz0DKwIdAzMCwEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQED/AEBAQEBAwEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEABQEBAQEBAQEBAAAAAAAIAAAAAAkADAAA1AEMAACEjPQUrBB0FKwE9CTsBHQE7BD0BOwEdCQMrBD0BOwQVAgBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAoBAQEAAAAEAAAAAAoADAABTAAAhKwY9CzsHHQE7AR0CKwE9AisFHQI7BR0BOwEdAisBPQIrBR0COwUdAQHAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAwAAAAACwAMAABkALQBHAAAhKwY9ATsGPQE7AR0BIx0BJSsBPQc7AR0GASM9ASsGPQE7Bx0BMx0BAkBAQEBAQEBAQEBAQEBAQEBAQP4AQEBAQAIAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEABQEBAQEBAQEBAAAEAAAAAAoADAABHAAAhKwY9CzsHHQE7AR0HKwE9BysFHQc7BR0BAcBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAABAAAAAAKAAwAAQQAAISsIPQs7CR0BKwcdATsCHQErAh0DOwcdAQJAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAABAAAAAAJAAwAAMQAAMyM9CzsIHQErBh0BOwMdASsDHQVAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAEAAAAAALAAwAAEQAlADkATwAAISsFPQE7Bh0BPQQrAT0BOwMdBSMhKwE9BzsBHQYBKwc9ATsIHQECAEBAQEBAQEBAQEBAQEBAQEBAQEBA/gBAQEBAAgBAQEBAQEBAQEBAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAcBAQEBAAAABAAAAAAKAAwAAPwAAISM9BCsFHQQrAT0LOwEdBDsFPQQ7AR0LAkBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAEAQAAAAUADAAAjAAAhKwI9ATM9ByM9ATsDHQEjHQczHQEBAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAMAAAAAAcADAAAJACEAKQAAISsBPQE7Ah0BPQo7AR0JIyErAT0BOwEVAQBAQEBAQEBAQP8AQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAEAAAAAAJAAwAACQAzADsAQwAAISM9AjsBHQIhIz0LOwEdBDsCHQE7AR0BKwE9ASsCHQQTPQE7AR0BIzc9ATsBHQEjAgBAQED+AEBAQEBAQEBAQEBAQEDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEABwEBAQECAQEBAQAAAAAABAAAAAAJAAwAAKQAAISsHPQs7AR0JOwYdAQIAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAACAAAAAAKAAwAAJwBHAAAhIz0HKwEdASsBPQE7AT0BOwE9ATsBHQshIz0LOwEdATsBHQErAR0HAkBAQEBAQEBAQEBAQP3AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEAAAAACAAAAAAKAAwAAHwBHAAAhIz0EKwE9ATsBPQQ7AR0LISM9CzsBFTsBHQE7AR0BKwE9ASsBHQgCQEBAQEBAQED9wEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAEAAAAAAMAAwAAEwAnADsATwAAISsGPQE7Bx0BPQg7AR0HIyErAT0HOwEdBgErBz0BOwcVAkBAQEBAQEBAQEBAQEBAQEBAQED9wEBAQEACAEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEABwEBAQAAAAAEAAAAAAoADAAA7AAAzIz0LOwcdATsBHQErAT0BKwUdATsFHQErBR0FQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAABAAAAAADAAMAABkALQBBAFUAACUzFSsJPQE7AzU7ARU7ARU9CDsBHQcjISsBPQc7AR0GASsHPQE7BxUCwEBAQEBAQEBAQEBAQEBAQEBAQEBAQED9wEBAQEACAEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEABwEBAQAACAAAAAAMAAwAABwBTAAAhIz0BOwEdASEjPQs7CB0BOwEdASsBPQErBh0BOwYdASMdATsBHQErAT0BKwE9ASsDHQUCwEBAQP1AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAAFAAAAAAJAAwAAEQAdACsAMwBFAAAhKwU9ATsGHQE9BDsBHQMjAysEPQE7BBUlKwE9ATsBFSUrBT0BOwYdAQGAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBA/sBAQEBAAYBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQAEAQEBAQEBAQEBAQEBAAAEAAAAAAoADAAArAAAhIz0JKwM9ATsJHQErAx0JAUBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAADAEAAAAKAAwAADQAlAD0AACErAz0BOwQdAT0KOwEdCSMhKwE9CTsBHQgBwEBAQEBAQEBAQEBAQP6AQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAFAAAAAAKAAwAACwAVAB8ALQA7AAAhIz0DOwEdAxE9AjsBHQIrAz0COwEdASU9BDsBHQQjISsBPQQ7AR0DAUBAQEBAQEDAQEBAQAEAQEBA/kBAQEBAQEBAQEBAQEABAEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEAAAAMAAAAAAoADAAAfAD8ARwAAISM9ASsBPQE7AT0HOwEdCyEjPQs7AR0HOwEdASsBHQEBKwE9ATsBFQJAQEBAQEBAQP3AQEBAQEBAQAEAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAEAQEBAAAAJAAAAAAKAAwAACwAXAB8AJwAvADcAPwBHAE8AACEjPQM7AR0DISM9AzsBHQMBKwE9ATsBFQU9ATsBHQEjNysBPQE7ARU9AjsBHQErAz0BOwEVJT0BOwEdASMhKwE9ATsBFQJAQEBA/cBAQEABgEBAQED+gEBAQMBAQEBAQEBAwEBAQEABAEBAQP5AQEBAQEBAQEBAQEBAQEBAQEBAQEABAEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAFAAAAAAKAAwAAEwAbACMAKwAzAAAhIz0HOwEdBxE9ATsBHQErAz0BOwEVJT0BOwEdASMhKwE9ATsBFQFAQEBAQEBAwEBAQEABAEBAQP5AQEBAQEBAQEBAQEBAQEBAQEBAQEACAEBAQEBAQEBAQEBAQEBAQAAAAAAEAAAAAAKAAwAAGwAjACsARwAAISsIPQE7AT0BOwEdATsFHQEBPQE7AR0BIzc9ATsBHQEjNz0BKwc9ATsJHQMjAkBAQEBAQEBAQEBAQEBAQEBAQEBA/oBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAEAQEBAQIBAQEBAgEBAQEBAQEBAAAABAAD/QAEAAwAAKQAAFysCPQ47Ax0BKwEdCjsBHQHAQEBAQEBAQEBAQEDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAACAAAAAACAAMAAAMACQANABMAFwAdACEAJwAAITUzFScjPQEzFScjNTMrAT0BMxUnIzUzKwE9ATMVJyM1MysBPQEzFQHAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAABAAD/QAEAAwAAKQAAFysCPQE7AT0KKwE9ATsDHQ7AQEBAQEBAQEBAQEDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAABQAAAYACAAMAAAUACwATABsAIwAAAT0BMx0BIT0BMx0BJSsBPQE7ARUFPQE7AR0BIzcrAT0BOwEVAcBA/gBAAYBAQEBA/oBAQEDAQEBAQAGAQEBAQEBAQECAQEBAQEBAQECAQEBAAAABAAAAAAJAAEAAEwAAJTMVKwg1OwYCAEBAQEBAQEBAQEBAQEBAQEBAQEBAAAMAQAJAAQADAAADAAcACwAAEzUzFScjNTMrATUzwEBAQEBAQEACQEBAQEBAAAAAAAMAAAAAAkACQAAfAC0APwAAISsFPQErAT0BOwE9ATsENTsBHQYnMz0BKwQdATsCEysGPQE7BhUCAEBAQEBAQEBAQEBAQEBAQEBAwEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEABQEBAQAADAAAAAAKAAwAAKwA3AEMAACErBj0LOwEdBTsBHQErAR0BOwUdAT0EOwEdAyMDKwM9ATsDFQHAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQAEAQEBAAAAAAAUAAAAAAkACQAANABUAIwArADkAACErAz0BOwQdAT0COwEdASMhKwE9BDsBHQMlIz0BOwEdAScrBD0BOwQVAYBAQEBAQEBAQEBAQED+gEBAQEABgEBAQIBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAgEBAQECAQEBAAAAAAgAAAAACAAMAACcAOQAAISsGPQY7AT0BOwM9AjsBHQsnMz0EKwMdBDsBAcBAQEBAQEBAQEBAQEBAQEDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAAAADAAAAAAIAAkAAEQAvADkAACErBD0BOwM1OwEdAiUrAT0EOwE9ATsFHQMrARUrAxU3MzUrAxU7AQHAQEBAQEBAQEBAQED+gEBAQEBAQEBAQEBAQEBAQEDAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAwEBAAAABAAAAAAIAAwAALQAAMyM9BisBPQE7AT0COwQdASsCFTsDHQErAx0GwEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAABAAA/wACAAJAAAsAMQA5AEUAAAErAj0BOwMdAT0FKwM9ASsBPQE7AT0BOwUdCiMhKwE9ATsBFRMzPQErAx0BOwEBQEBAQEBAQEBAQEBAQEBAQEBAQEBAQED+wEBAQEDAQEBAQEBAQP8AQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAYBAQEBAAAAAAwAAAAACAAMAAA8ALwA3AAAhIz0FOwEdBSEjPQs7AR0FOwEdASsBHQMBKwE9ATsBFQHAQEBA/kBAQEBAQEBAAQBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAYBAQEAAAAIAAAAAAIADAAAVAB0AADMjPQg7AR0IAyM9ATsBHQFAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAKAQEBAQAAEAAD/gAHAAoAACQAbACMAKwAABSsBPQE7Ah0BPQc7AR0GIyErAT0BOwEVASM9ATsBHQEBAEBAQEBAQEBA/wBAQEBAAQBAQECAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQAHAQEBAQAAAAAQAAAAAAgADAAAHAC8ANwA/AAAhIz0BOwEdASEjPQs7AR0FOwEdATsBHQErAT0BKwEdAxM9ATsBHQEjNz0BOwEdASMBwEBAQP5AQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAYBAQEBAgEBAQEAAAAAAAQAAAAAAgAMAABsAADMjPQs7AR0LQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAAAAQAAAAAA4ACQAARACMAQQBNAAAhIz0GOwEdBiEjPQY7AR0GISM9CDsFHQErAx0GASsDPQE7AxUDQEBAQP5AQEBA/kBAQEBAQEBAQEBAQAKAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAcBAQEAAAgAAAAACQAJAABEAMQAAISM9BjsBHQYhIz0IOwYdASsEHQYCAEBAQP4AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAQAAAAAAgACQAALABkAJwAzAAAhKwI9ATsDHQE9BTsBHQQjISsBPQQ7AR0DASsDPQE7AxUBQEBAQEBAQEBAQED+wEBAQEABAEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEBAAQBAQEAAAAADAAD/QAJAAkAAKQA1AD8AABcjPQs7AR0BOwEdASsBHQE7BB0BKwQdAwE9AzsBHQMjAysCPQE7AhVAQEBAQEBAQEBAQEBAQEBAQEABQEBAQEBAQEBAQEDAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAYBAQEBAQEBAQAEAQEBAAAIAAP9AAgACQAApADsAAAUjPQIrAz0BKwE9BDsBPQE7AhUzNTsBHQsDMz0DIzUrAh0EOwEBwEBAQEBAQEBAQEBAQEBAQMBAQEBAQEBAwEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAUBAQEBAQEBAQEBAAAAAAAEAAAAAAcACQAAjAAABNSsCFSMdBSsBPQg7ARUzNTsCFTMdAQGAQEBAQEBAQEBAQEBAQAGAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAAFAAAAAAHAAoAADQAVAB8AJwA1AAAhKwM9ATsEHQE9AjsBHQEjJysCPQE7AhUnKwE9ATsBFSUrAz0BOwQdAQEAQEBAQEBAQEBAQEBAQEBAQEBAQMBAQEBAAQBAQEBAQEBAQEBAQEBAgEBAQECAQEBAQEBAQEBAQEBAAAAAAgAAAAABQALAAAcAIQAAISM9ATsBHQEnKwE9BCM9ATM9ATsBHQEzHQEjHQMBAEBAQIBAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAgAAAAACAAJAAB0ALwAAISsEPQE7Az0GOwEdCCUrAT0GOwEdBQHAQEBAQEBAQEBAQED+gEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAQEBAQEBAQEBAQEBAQAAAAAAFAAAAAAKAAcAABwAPABcAIQArAAAhIz0BOwEdAT0COwEdASsDPQE7ARUlPQI7AR0CIyErAT0COwEdAQFAQEBAQEBAwEBAQEABAEBAQP5AQEBAQEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQAACAAAAAALAAgAAJwA3AAAhKwc9ATsCPQI7AR0COwE9BTsBHQclKwE9BTsBHQQCgEBAQEBAQEBAQEBAQEBAQEBA/cBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQEBAQAAAAAAJAAAAAAKAAoAABwAPABcAHwAnAC8ANwA/AEcAACEjPQE7AR0BISM9ATsBHQElKwE9ATsBFQU9ATsBHQEjNysBPQE7ARU9AjsBHQErAz0BOwEVJT0BOwEdASMhKwE9ATsBFQJAQEBA/cBAQEABgEBAQED+gEBAQMBAQEBAQEBAwEBAQEABAEBAQP5AQEBAQEBAQEBAQEBAgEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEAAAAAAAwAA/4ACAAJAAA8ALQA7AAAFKwQ9ATsFHQE9AisDPQE7Az0EOwEdCCMBKwE9BDsBHQMBQEBAQEBAQEBAQEBAQEBAQEBAQEBAQED+wEBAQECAQEBAQIBAQEBAQEBAQEBAQEBAQEBAQEABAEBAQEBAQEBAQAADAAAAAAIAAoAAFwAfADcAACErBj0BMz0BOwEdATsEHQEBPQE7AR0BIzc9ASsEPQE7Bx0BIx0BIwHAQEBAQEBAQEBAQEBAQEBA/sBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEABAEBAQECAQEBAQEBAQEAAAAADAAD/AAFAAwAABwAnAC8AAAEjPQE7AR0BJysBPQUjNTM9BDsBHQQjFTMdBBE9ATsBHQEjAQBAQECAQEBAQEBAQEBAQED/AEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEACwEBAQEAAAAABAAD/AACAAwAAIwAAEyM9DzsBHQ9AQEBA/wBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQAADAAD/AAFAAwAABwAnAC8AABMjPQE7AR0BPQYzNSM9BDsBHQQzFSMdBSMDKwE9ATsBFUBAQEBAQEBAQEBAQEBAQED/AEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAwBAQEAAAAQAAAFAAoABwAAHAA0AEwAbAAABMxUrAjUzITMVKwE1JTMVKwE1BysCNTsCAcBAQEBAQP7AQEBAAkBAQEDAQEBAQEBAAYBAQEBAQEBAQEAAAgBA/0ABQAIAABcAHwAABSsCNTM9BjsBHQYzFQMjPQE7AR0BAQBAQEBAQEBAgEBAQMBAQEBAQEBAQEBAQEBAQEBAAkBAQEBAAAAAAAgAAP9AAgADAAAFAAkAJQAtADMANwBLAFEAABU9ATMdAT0BMxU3KwI9ASsBPQU7AR0EMxU7Ah0BPQI7AR0BIyU9ATMdAT0BMxU3KwE9ASsCPQE7Ax0BOwEdAQM9ATMdAUBAwEBAQEBAQEBAQEBAQEBA/wBAQIBAQEBAQEBAQEBAQIBAwEBAQECAQEBAQEBAQEBAQEBAQEBAQEBAQIBAQEBAQEBAQECAQEBAQEBAQEBAQEABAEBAQEAAAAAAAQAAAAACAAMAAD8AACErBj0BMzUzPQErAT0BMz0CMzUzNTsCFTMVMx0BKwE9ASsCHQI7Ah0BKwEdASMVOwQdAQHAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAACQAAAEACQAKAAAMABwALACsANwA7AD8AQwBHAAAlNTMVITUzFSUjNTMHKwE1IxUjNTM1Iz0CMzUzNTsCFTMVMx0CIxUjFSczPQIrAh0CMxM1MxUhIzUzITUzFSEjNTMCAED9wEABwEBAwEBAQEBAQEBAQEBAQEBAQEBAQEBAQMBA/oBAQAGAQP4AQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQECAQEBAQEBAAQBAQEBAQEAABwAA/8ACQALAADEANQA5AD0AQQBHAE0AAAU9ASsDPQE7AzUrAz0BOwI1OwIVOwIdASsDFTsDHQErAx0BEzUzFSEjNTMhNTMVISM1MyE9ATMdASEjPQEzFQEAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQED/AEBAAQBA/oBAQAGAQP4AQEBAQEBAQEBAQEBAQEBAQEBAQAIAQEBAQEBAQEBAQEBAQAACAED/AADAAwAAEQAjAAATIz0GOwEdBgMjPQY7AR0GgEBAQEBAQED/AEBAQEBAQEBAQEBAQEBAAkBAQEBAQEBAQEBAQEBAQAASAED/QAIAAsAAAwALABMAFwAbAB8AIwApAC0AMQA1ADsAPwBDAEcASwBRAFkAAAE1MxUDMxUrAjU7AT0CMx0CISM1MysBNTMlIzUzMTUzFSsCNTsCNTMVISM1MyEjNTMFIz0BMxUhIzUzKwE1Mwc1MxU3IzUzKwE9ATMVNysCNTsCAYBAgEBAQEBAgED/AEBAQEBAAQBAQECAQEBAQIBA/sBAQAEAQED+wEBAAQBAQEBAQMBAQEBAQEBAwEBAQEBAQAJAQED9QEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAIAAAKAAUADAAAHAA8AAAEjPQE7AR0BISM9ATsBHQEBAEBAQP8AQEBAAoBAQEBAQEBAQAAXAAAAAAMAAwAAAwANABEAFQAZAB8AIwAnACsALwAzAD0ARQBPAFMAVwBdAGEAZQBpAG0AcQB7AAABNTMVAzMVKwM1OwI1MxUhIzUzITUzFSUzFSsBNQcjNTMhNTMVITUzFSsBNTMHIzUzIT0DMx0DISM9AjMdAQcjPQMzHQI3NTMVJSM1MwUrATU7AQU1MxUlIzUzBTUzFSUjNTMFNTMVJSsDNTsDAcBAQEBAQEBAQECAQP7AQEABQED/AEBAQIBAQAHAQP8AQMBAQMBAQAJAQP4AQEDAQEDAQAGAQED/AEBAQED+gEACAEBA/gBAAYBAQP6AQAEAQEBAQEBAQEABwEBA/oBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAgEBAQEBAQEBAQEBAQEBAQEBAQEBAQAABAAD/wAJAAwAATQAABSsBNSM1IzUjNSM9ATM1Iz0BMz0BMzUzNTsDFTsBHQErATUrAhUjFTsEHQErBBU7Ax0BKwMVMxU7AjUzHQEjFQGAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAAAAAAAAOAK4AAQAAAAAAAAAOAB4AAQAAAAAAAQAJAEEAAQAAAAAAAgAGAFkAAQAAAAAAAwAYAJIAAQAAAAAABAAJAL8AAQAAAAAABQAQAOsAAQAAAAAABgAJARAAAwABBAkAAAAcAAAAAwABBAkAAQASAC0AAwABBAkAAgAMAEsAAwABBAkAAwAwAGAAAwABBAkABAASAKsAAwABBAkABQAgAMkAAwABBAkABgASAPwAQwByAGEAZgB0AHIAbwBuAEcAYQBtAGkAbgBnAABDcmFmdHJvbkdhbWluZwAATQBpAG4AZQBjAHIAYQBmAHQAAE1pbmVjcmFmdAAATQBlAGQAaQB1AG0AAE1lZGl1bQAAQwByAGEAZgB0AHIAbwBuAEcAYQBtAGkAbgBnADoATQBpAG4AZQBjAHIAYQBmAHQAAENyYWZ0cm9uR2FtaW5nOk1pbmVjcmFmdAAATQBpAG4AZQBjAHIAYQBmAHQAAE1pbmVjcmFmdAAAVgBlAHIAcwBpAG8AbgAgADAAMAAxAC4AMAAwADAAIAAAVmVyc2lvbiAwMDEuMDAwIAAATQBpAG4AZQBjAHIAYQBmAHQAAE1pbmVjcmFmdAAAAgAAAAAAAP+AADMAAAAAAAAAAAAAAAAAAAAAAAAAAABuAAAAAQACAAMABAAFAAYABwAIAAkACgALAAwADQAOAA8AEAARABIAEwAUABUAFgAXABgAGQAaABsAHAAdAB4AHwAgACEAIgAjACQAJQAmACcAKAApACoAKwAsAC0ALgAvADAAMQAyADMANAA1ADYANwA4ADkAOgA7ADwAPQA+AD8AQABBAEIAQwBEAEUARgBHAEgASQBKAEsATABNAE4ATwBQAFEAUgBTAFQAVQBWAFcAWABZAFoAWwBcAF0AXgBfAGAAYQECAKMAhACFAL0AlgDoAIYAjgCLAQMBBAd1bmkwMEEwBEV1cm8HdW5pMzAwMAAAAAAB//8AAgABAAAAAAAAAA4AFgAAAAQAAAACAAAAAQAAAAEAAAAAAAAAAQAAAADH/rDfAAAAAMh4K0EAAAAA0b9amA==";
const CLICK_B64 = "SUQzBAAAAAABAFRYWFgAAAASAAADbWFqb3JfYnJhbmQAZGFzaABUWFhYAAAAEQAAA21pbm9yX3ZlcnNpb24AMABUWFhYAAAAHAAAA2NvbXBhdGlibGVfYnJhbmRzAGlzbzZtcDQxAFRTU0UAAAAPAAADTGF2ZjYwLjE2LjEwMAAAAAAAAAAAAAAA//tAwAAAAAAAAAAAAAAAAAAAAAAAWGluZwAAAA8AAAAIAAAJxwBdXV1dXV1dXV1dXV2IiIiIiIiIiIiIiIioqKioqKioqKioqKiowsLCwsLCwsLCwsLC3d3d3d3d3d3d3d3d3erq6urq6urq6urq6vX19fX19fX19fX19fX///////////////8AAAAATGF2YzYwLjMxAAAAAAAAAAAAAAAAJAYwAAAAAAAACcdIPZOqAAAAAAD/+8DEAAAAAAH+FAAAJB2yqr81lkBFp6tZNUNGNlKRhEsAkAiU0qEzpczwJBOegYISRuxpmS5jRgJPmkSEKFAUCihowCeoiHGUBagMww1ETuMLdv2mOusFEJLixZoip8gEV11SKAMkZxKm4phhBZsllp1fqDtPvpiNZYJUsQYoIXQfVl5fsYAl8bn/jFK4i72Jv2yh7GgK3reSIWOlXD7+Szmc3L6Nx33dd3Jykhap2DyRXcFuXG7f8qWKfKxFLtO/jgQJT09O5cBMkhaqjUKO3f//ciWv25cP9+YjdP7lsrgeG4XSfmnRhxdDEGsLhW/L/uyynysU9PbpMPpMP/2J/JKKchuj7V6y+min+9CYFvjWHM6nw8DOHjUvZ2qkRxRQAhEwQgWCEMhIJF2UlVBCDXRqxmRRKk+ZVawIhkJAwCgAwjD1SqMTZwANEJ5Ap0fwJFCc+gAUlGgaIkxdF4HvcYFLITJ6R+ChGCkjE2xVI2EMpaa5LzIbQE4TbU1V2VgXYjdJAczJVpROIwZArivJD1VnDysmT5swI87sdqRbVNLmJW7MQkjTrM7FKWnlMC6g5lTZXShqBHcvfdfZnVSw5UBRa7rC5MyyW0tWtS0L/vFMxWU3pR+7fYnAUnpLdR/u8j9aUTfZFTT+NX6Wr/ym99W5GrtSXf8Q1/4fzDXLdzdjsavf+8O7pO6ywtX/n8m3A0VtsIqc6osEnC7wWPmOHmACNAEg7jLZSyUzR6WWwWlXLgPo4JRobD6XAnvNjAvH0B6AS9Y1KUR2JvWWPRF70Tsta6pSdta+Ux0tUZ7t0VudtXYk3pZ51rYcZnF4a2W8XXve2p+3cco026mJdcHodzEubX9VUdSa7HfzPvvuf2O4uL/j5a35v/ukMQay1afKmFMjIJsEmcwgVpYOMKQvMAYCGiQSWdTELiq5aZHZQv93Z5/qWQUMcylVDe3FAy82ThKq2ZnSJi9wrf/7kMTfAB4RmWn5nAJCQ7Gsf7SwBcSwwtqnWeUYWc6289qZ1SRUaN7+pZ7/yaw47UZah0rzSlcuR2ysup5Lb/RRZSiwGZhEMmSw8FSW7rGBxg25R5YKD2S1ZlIhFhIlO4OUMIayHHMqkm3eJjvylatUKBb53kMoaZAyqVtrC5DuxRxU45MUPJFghpAiN5rW0XK5CtSKtpNnSeNS2OPMOnnUyiq1y4SlN6QlTU0Fb02GDX6RAhNPqlm2UFEDCoYNMqZkyGDL7uiAJqHBQNwzOyxorP9bmnjpYOAqefMKSNeEIBECkiSrRRZXAzkOzj2Q/LQcLMl8y0ReJJJ21gXNgR/3VgiHtUE/FZNFji0OY017OQlgiHGwIw9A+OmF5KFSWPN79oDkVHU00hRRRTTXAqn9lB8tTUk0SJdU+qoaWl0mYu9IidgZUrP7w8UPiinRjcNhSBHLhr3thv33pLEiLFOQsM7yhmIJMopSBYIOKjgFVI1IJQNFsKAVHpRVElwVMXNgx221mLVHElpgyU2C9HRCWEiW2RQJfUgETIkcr48v5v/7cMTkAA/BM1nsGLOiFaXo/YMOaDtU/LOJkE0aaCRpsl52Y6WwozOqtyir/7N9VRJuS//hqQMEapkKYV+CdeqWqPf9SpGaklKMdRkpiT9nz/uzH/BNAKjeVdtd/GjFfSngxs0V9WI5l5ozAawGJ+QA0kicMJrcVMqoKtpKRqjgqq8kvzSMOjKRjtt1VEk5in9ve8pebMpHGnTOx651zvxdejHODqFXzB6ZLs5F1VYMY3xrqTRmzULIGFAQ+t2p8sWfgahNTGprGDgMeGB4rnZHddbLmmgAMo51S49L37T4eRoZhMLN1rhvFHb2cx09R9WaRPtGwQpMN4pz0cRJGmrRfJiH1AsqOHKN5cPjcOQtnUqUc6GgYwg/GqiIiSdhcY79btfr89bZ+bUqaSSUbbsjRAAzW3pbOlD/+2DE9AAQfUU97CBzghExpj2DDjFwQFs0KMF0ByM3MjwQCCoCYzwyrEwkWJUKDUwp+Wb+SqQ4caVZ/YzXY0HS2G2JMpjA5q5aF2TruxPkdJ6t2ojbmudS87WA+qgAd+o86njFHnTLdzSDtKVA0VMRERUe1/b/17KvZRVMQU1FMy4xMDBVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVUxBTUUzLjEwMFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+2DE54AOlR0jh5hzgW4b4/TDDmBVVVVVTEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+yDE9wAKZMEZoYRgQIEAIlgAAABVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//sQxNYDwAAB/gAAACAAAD/AAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVX/+xDE1gPAAAH+AAAAIAAANIAAAARVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVQ=="; // tu minecraft-click.mp3 (recortado y normalizado)
const BOW_B64 = "SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU3LjgzLjEwMAAAAAAAAAAAAAAA//tAwAAAAAAAAAAAAAAAAAAAAAAASW5mbwAAAA8AAAAUAAARCQAWFhYWIyMjIyMvLy8vLzs7Ozs7R0dHR0dUVFRUVGBgYGBgbGxsbGx5eXl5eYWFhYWFkZGRkZGdnZ2dnaqqqqqqtra2trbCwsLCws7Ozs7O29vb29vn5+fn5/Pz8/Pz//////8AAAAATGF2YzU3LjEwAAAAAAAAAAAAAAAAJAWAAAAAAAAAEQkRXhDVAAAAAAD/+1DEAAAGiBEW4xhgAVuNY+TzChgAQCSCUYEMAZw1Dm4QNE6j8utJCICeT4g7j43Ka//KF3o69/18uOdjqVFLTl6CeQiD+U0lARboYAAA/gbJJyXkjJeQQ5GiGeizBVStONySC1JEkGFrRpNN9QSl2VEk8KaEJ32hDgqfHgg1ZqSUXKFL11AgECoIQffRSo4Hz8L1RSlnNLf7kp9H//k0KgeVZXqXn/a23OeY+r9n5l5naSoOg+/ia68GWKASx/F+P3AjEE55iHJzGhp33T4m//tSxBeAD+UtQeyYd2lwkKkBrBi4oEgiSyqHLkffwIERZLB4WGQ9s6ZirF0hNu06z2vW+n20OfsRffaVKZ1dkDIiEBEoO2EIy1MYqIu21IVa1ASFI8O/vEX3egaJ0yBta8E9yASdVGMFigaYcOqZrEtESC9J2MCWl7kBptSw5bKzkrJQ/+VPuXug+r5rriF6UGhdRhmH7Hcm3+PcPbUgDnIE0zFEHWEQIcCJ84f9QWFgiBHEwiBMhUAG//pZ/s/6OmpO84TgPwk41YHBqUUyS6L/+1LEB4PL0HdeDLDOgXAbK4GUjdh6BijJKKhgBg1KywA00/ZXHo/lgdgYkogPmDZq2BFH0icqD93T6QKjPZjqSRBAVB08LA4kFiYsLAR73Q8wZKGVZxsKkv59aKVscufk8V/+9LUxkTSFjkPr/TLRzY7LGIuyXFTvLjnMOodfGiKNoFTlPZPCFZEqyjjoDERq/VFOQYehR38cUoqvSCUQ+CfTNrXDQ5lkeQPL7LTggpR59KFxZb0bF7nGV6lXP2aKQIAAL3LCj0rMX8uAthFn+v/7UsQIAAwEo1rHmG7BgI+rdPMN4ByEG4QaodDOcCAXllbZyikmwjkXtWbGUPRsKGbEmfcqoNlsunVQ36pBhgOrDUdCYKjwVOtb12ClB5REJxZaqdLrjrpIA0Gig1wicBaqk1aXVpEAogIktJwM8/C+noX9ZQBeFOiE6HEGqjniq3EvQ8bIACy4OOOW0slkTNyX6pHfSkfSpOsWDguoVjwKLRQXA4mPvLy5dizJY9i51ctT3KPO62tPJU/Wm8GXETJVoselqlgCCCAAAAUoME5C//tSxAWAC1xXT6eYbkF/i+q09hg07IlwHisluS6ubCrU67OA5k1QJojSGJHB5h6BbuLkPUGw4ULLBUYPcCRkSgGPWgWKsDrKLLUCQwbrDAuCWdehquierYr65hPPA3hWgs6entfcrjDbSbZTlDhOgD1AyPSuQ0AwXg0JJgAgv9YkOtq0k7r55xVScn6beXjMdgoBTwPvEIUDwdmwTcEhMTHObUVM3AcPG0B0FRz5EyJhWIooTPBWkBXJvDsBTvkeDJPK6ao5sAAAIIrhfjeGeO7/+1LEBgELqM09h6RvAXIT5uT0jdk5ChXRbS7M0onzMMUuhjH6ynzplZomJmBtOWkPyLo6iWW8tZWIRDvGooEVBcOzL9GPaZn1Wux2+TWpsYVgq3oEVBYDAYcHUIln6OPceZDQu7rVMAFbLjFiIklS8rzgQlJF4QYaSdLEZRLtFGhpUrpGFmnIpIJMTtM0TiSEPQHNX1E04ZHdcz2OiD2OQgphszZ9FLofNNr1vp8j+Pp6KNe6k3+WlFba7xN6un83Z/I3AAAABjwCwnkT4eouV//7UsQHAcswczEnpM6JY5HlQYYN4SfvThIUaQwyEgBKaYgvlqqFTAKAUcgfoujSfI4aCKSnWqYtHGnujJQprGCi7Ts6szTlHWuSdZ5O2b9zX5cDxyrdzsH/2Q/6FfS2Qdr0EGPixVmTjIljgEtiAItFhSqbWF4NbYqBYaBCLagdTckhEPhZZHU69o5MInU7Dp3TDlxHvHUrSQX1hwTpGDBV9jnZc8cApnw5B/oSM03OcdaGZl3/lZ1flRCQAAAAtYSwD/JwoCFtBpIlYRQ8DmQq//tSxAuBCgx/MYekbolGkqUU/BjgUgStZRYQh47SZk4Ra1zL8igOr1Com9kLrRmyzGeGPZ8G+wVMkhRAuVGrBl/Sdxtrv++vi/tyY32SiiGQWI/jAXA9y5IgQLUyb6BWusZlCIrX1hoLfu3TJYEohZAgQCRgMeokOUFFOlPOOQtvmJPGZMVueyTZTX/iLxUjSeRfF1mQi6MGLWJtK6e1iUAAAwHcFEc5MgkYAIVgQhJgsAZ4kAySSh8MhWQmfHlLActOnhT2Np6z1X0FhbDwaOL/+1LEGIGKBM8mx7BtCUAPpET2GdFejKkikx1Ak0Ms3JvuRF1sjKHoyp5WhVjCzG0d479L4kYj/NAnA1igLiTFDhhDPJa8VosQiqQ4roRVaJ5sXRYVl0B+AQGK0jpFMvxCNIzv0yqmJ3viPQeBOiqm6qvCxa570yXOeAivpij3O9+///2quTL8xdlbIEk1+g0RhE3N+lKb0LE1AKhMTBISTU2DhOuMV6iz7cHLjyFP83euxQiuTfHPYjTfhoYOqph7RRqg4EDdDzrwGtDr/FP////7UsQmAAnwlR4MMG1BSpGj1PYNaP///pCISGGFUOn4jAtYQ03THfiTCOB1BAMfjiWYDM9O2yaIyZ4mXojaZZ/taHQKqgrgwU1do5OZCLTu4SqMh4RHAQPHVIAZhg1SbTy7JCRq///////1VTBKNN0PtJqw0SckoKxRIpFqCGhhqNTSy2OobXR4rf1hP2xqqxBhMKB1CVNMrUJ3PBlzUi4mOwMN2hQfjK7P/duX+W/Nvv///qAQJKKdkiwievTRYxZdkuDYR66G8OZ6BopqSwYv//tSxDKACRBNIsE9IYE0kGOY9g2gtNxutmNXFz0Oe6UjZhB0jfmK8MaqvkwMGWpBpoAh4CnQgbi58A7aK/ty//f0fW3/SgCCBAtMkyDkSZKDJ83l8JEQ5QH+Q1FIVZdYClzWapgCgy3Qo2pGsNkX8bddaZoPRhU+GkizA8ZYMSaJCQX12YaF2ISvLUd/1afT//3dDQtjEhjMQ03lchpQQAwAwyCsjwnMZBBqSaNzluowouFUeoLYMgFFOQgyDj50iP81LzNmSAyFmAGJDVrdTHL/+1LERYJJrIEap6RuQSgTI0j0jSijkfJ+um+jyKEf//0VkQAE11a1gtoAAoFiwgGsBpEkx81MmmYC7iRkCaMeoHgE1rf6w0amqmIFw0QBbTURJvdSBXGRZcMjGXpQXDqLkpIX+Kd3/7f+oTKgpisa6m5nEIoHYjEsHKJ5USvimcVMDCVk2lFKhnSFhKhx2izhLqOYQJQULjSRoucAG3eXqIGxzYvW3Vsvc7/6Pktf+msAJgcwSgmAcSSFEy2qjIpkcIfOte1Wj1ZL5d5exE7ud//7UsRXggkQdxhGGGmBGg5jWMQN2G3h3gWlT4OHQMHnkL0nkxK4kHUiIG3whe1vQ/ndC6I6rRhVH2p7850rA1IA8yKNxLeaBmSxOiTpVFXl6iKni1G2lgsPHxNCYEBwSgqbBFEgACJ3rQTV6EWpxT/Y1iNX/f9rfs7fvT8mGQAExsBAQicSlR7KJYiTwMQLc1TKyN1ybXd5tlSZKmpBYrHmLIQDTB5RpLT2qtofLGX17UV9jXLZdd1/uRotWAfI1+r5OymHDegvXjjuDLBiVX5k//tSxG4CSQx5FqYEdED+CGLI9gxozkWUHhoXGkl3orcJnyVsi2t1CKDZtCyTIiNpyaCrNU7tL6HvLn0r3QzG5Je3ZX0FfkYAAAnagaAiQQDY4h2KpqbpetRzRdvcfUc/M0s5GB/JwzZGvcqNiyoogyVlePxFQEe+QAfHliMyAj38WUgo0YVDNKDn2a//ngv+DQDuqiCQKjzrlFoebaWYECO1amStG8u2aMWim2WZyk2+GvMqVs4eRlXtz+rZ/FuXg8SIln1CoHC5IN5kAUgC54H/+1LEiAMIsG8URgR0QQEHYkRnjAgFxMAxMwHq/Kkhr8rVAFsUo01zQj5GYzxJy2pfis5wzhZEZFfQpflae8JLxNXmRNpDGyfUo3opI0L/p9NMFuT8k2/hKWRjmuH+EboR7svnS4VQY0D1z0CO+DP//4AF48p/3ByJgc3UN4qyJhKGxLB1XUukT5E5I5VDjeZZ8u1C0l7C2LKxJM49kWytecRCcYrI5ZCLUg0aMKQq4uphAUtud2ZS3Hyop3VBNaPqZ0a53lnIJiByaSRv/GC7Uf/7UsSjAgk5kREEBFfBMZ0hRGCOKPg6/oTVqzeDqu5mpn/cU5dilN9DUnySymZZFsNxzL0qn7PaNiHB5OBqczPbp/zbRB3LtDsoWdqSsioRqKc+gH9VHYExtRYUETCigNDa7ZKrBh8axY153+MFW+oJ/3nP5Cs8pfm5SnhXXjrzK181TfD0UT6Vyn05O1I12pjVMtddr7a00U+nMWZqry1FUfR6ueFEf//NzzTvxznq5gtN1NbERfFYLFaB/lks//HTN/44T6O2ISFiusCQ/qq///tSxLWDymWDBgAYYoF2MWDAYZX4nBUN4WP+gedp/xgAjoUP4UBgOiZgywoljhOphyaoxEhZH0KJZDMlhtYF5fnXSKxVxzV0hphsh2WyxVn7a2//8U/xb2OHYtwFRZBo7YqSJmn3FlLY502o/9NDlFN/tC7nGCU4faxdETl8////SDv//wFWgo/0KWGFaGQUrTKVuVYetUlVV/jHGP/UmPLjcbqyCjVYzMpBgJuM2zVf/+AR7KcaqqiQwlcGAo3WZmYy1Zv1UgxepSkDzB4PDyr/+1LEuwPLPYsEAYy3waSvX8BjFvg4iAIe/5lL1KodagM9ymUEh2f2VP/6Kn6Kn6L////RUZ2/9SccXF5v///+ycWXF5qJIFFChZBNSSJxpcbn8s7tebNOyK3lMJKQ7f7GKiqzsYokIhQwTEq1TEFNRTMuMTAwVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVf/7UsS3gk0pbPICjS3BUS3c1CGWuFVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV//tSxLaDyY1slCEYvogAADSAAAAEVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVU="; // tu bow_shoot.mp3 incrustado (se puede reemplazar con un archivo bow*.mp3 en la carpeta)

/* ======================= Íconos pixelados ======================= */
const PALETTE = { X: "#000000", W: "#ffffff", R: "#d92b2b" };
const MAPS = {
  heart: ["..XXX.XXX..", ".XRRRXRRRX.", "XRWRRRRRRRX", "XRRRRRRRRRX", "XRRRRRRRRRX",
          ".XRRRRRRRX.", "..XRRRRRX..", "...XRRRX...", "....XRX....", ".....X....."],
  bubble: [".XXXXXXXXXXX.", "XWWWWWWWWWWWX", "XWWWWWWWWWWWX", "XWWXWWXWWXWWX", "XWWWWWWWWWWWX",
           "XWWWWWWWWWWWX", ".XXXWWXXXXXX.", "...XWWX......", "...XWX.......", "...XX........"],
};
function svgUrl(w, h, cellFn) {
  let rects = "";
  for (let y = 0; y < h; y++) for (let x = 0; x < w; x++) {
    const c = cellFn(x, y);
    if (c) rects += `<rect x='${x}' y='${y}' width='1' height='1' fill='${c}'/>`;
  }
  const svg = `<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 ${w} ${h}' shape-rendering='crispEdges'>${rects}</svg>`;
  return "data:image/svg+xml;utf8," + encodeURIComponent(svg);
}
function mapIcon(name) {
  const rows = MAPS[name];
  return svgUrl(rows[0].length, rows.length, (x, y) => PALETTE[rows[y][x]] || null);
}
function grassBlockIcon() {
  const greens = ["#5cb83a", "#4a9c2e", "#6fcf47"], dirts = ["#6b4d32", "#5a4029", "#4a3321"];
  return svgUrl(16, 16, (x, y) => {
    if (x === 0 || y === 0 || x === 15 || y === 15) return "#000";
    const h = (x * 7 + y * 13 + x * y) % 5;
    if (y <= 4) return greens[h % 3];
    if (y === 5) return h % 2 ? greens[h % 3] : dirts[h % 3];
    return dirts[h % 3];
  });
}

const TOASTS = {
  server:  { title: "¡Desafío completado!", challenge: true,  icon: grassBlockIcon },
  joined:  { title: "¡Logro conseguido!",   challenge: false, icon: grassBlockIcon },
  friend:  { title: "¡Logro conseguido!",   challenge: false, icon: () => mapIcon("heart") },
  voice:   { title: "¡Logro conseguido!",   challenge: false, icon: () => mapIcon("bubble") },
  message: { title: "¡Logro conseguido!",   challenge: false, icon: () => mapIcon("bubble") },
};

const CSS = `
@font-face { font-family: "MinecraftLogro"; src: url("data:font/ttf;base64,${FONT_B64}") format("truetype"); }
.mcl-container { position: fixed; top: 18px; right: 18px; z-index: 2147483000; display: flex;
  flex-direction: column; gap: 10px; pointer-events: none; }
.mcl-toast { display: flex; align-items: center; gap: 12px; width: 340px; min-height: 68px; box-sizing: border-box;
  padding: 10px 14px 10px 10px; background: #1b1b1b; border: 4px solid #000;
  box-shadow: inset 0 0 0 2px #5a5a5a, inset 0 0 0 4px #2b2b2b, 6px 6px 0 rgba(0,0,0,.5);
  font-family: "MinecraftLogro", monospace; -webkit-font-smoothing: none; image-rendering: pixelated;
  transform: translateX(120%); animation: mcl-slide var(--mcl-dur, 6s) forwards;
  animation-timing-function: steps(8, end); }
.mcl-icon { flex: none; width: 48px; height: 48px; display: flex; align-items: center; justify-content: center;
  background: #3a3a3a; border: 2px solid #000; box-shadow: inset 2px 2px 0 #7a7a7a, inset -2px -2px 0 #1e1e1e; }
.mcl-icon img { width: 32px; height: 32px; image-rendering: pixelated; }
.mcl-text { min-width: 0; flex: 1; display: flex; flex-direction: column; gap: 6px; }
.mcl-title { font-size: 16px; color: #ffff55; text-shadow: 2px 2px 0 #3f3f15; }
.mcl-challenge .mcl-title { color: #ff55ff; text-shadow: 2px 2px 0 #3f153f; }
.mcl-name { font-size: 16px; color: #fff; text-shadow: 2px 2px 0 #3f3f3f;
  overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
@keyframes mcl-slide {
  0% { transform: translateX(120%); } 7% { transform: translateX(0); }
  93% { transform: translateX(0); } 100% { transform: translateX(120%); }
}`;

const KINDS = ["place", "break", "bow", "logro", "desafio", "click"];
const MIMES = { ".ogg": "audio/ogg", ".mp3": "audio/mpeg", ".wav": "audio/wav" };

module.exports = class MinecraftDiscord {
  constructor() {
    this.defaults = {
      bow: true, bowMentions: true, bowVolume: 0.8,
      clicks: true, rightClick: true, pitch: false, clickVolume: 0.5, clickStyle: "boton",
      server: true, friend: true, voice: true, message: true, logroSound: true, logroVolume: 0.6, duration: 6,
    };
    this.settings = Object.assign({}, this.defaults, BdApi.Data.load(PLUGIN, "settings") || {});
    this.sounds = {}; this.urls = [];
    this.seen = new Set(); this.spoke = false; this.messaged = false;
    this.connectedAt = Date.now(); this.lastClick = 0; this.bowMode = "-";
    this.onClick = this.onClick.bind(this);
    this.onContext = this.onContext.bind(this);
  }

  get folder() { return path.join(BdApi.Plugins.folder, PLUGIN); }
  save() { BdApi.Data.save(PLUGIN, "settings", this.settings); }
  get me() { return this.UserStore && this.UserStore.getCurrentUser && this.UserStore.getCurrentUser(); }
  get warmedUp() { return Date.now() - this.connectedAt > 8000; }

  /* ======================= Ciclo de vida ======================= */
  start() {
    BdApi.DOM.addStyle(PLUGIN, CSS);
    this.container = document.createElement("div");
    this.container.className = "mcl-container";
    document.body.appendChild(this.container);
    this.connectedAt = Date.now();

    this.loadSounds();
    document.addEventListener("click", this.onClick, true);
    document.addEventListener("contextmenu", this.onContext, true);

    this.stopped = false;
    this.setupBow();
    this.connect(0);
  }

  /* Busca el dispatcher y los stores de Discord; reintenta por si Discord todavía está cargando. */
  find(tries) {
    for (const t of tries) { try { const r = t(); if (r) return r; } catch (err) { /* prueba el siguiente */ } }
    return null;
  }

  connect(attempt) {
    if (this.stopped) return;
    const W = BdApi.Webpack;
    this.Dispatcher = this.find([
      () => W.getByKeys("subscribe", "unsubscribe", "dispatch"),
      () => W.getModule((m) => m && typeof m.subscribe === "function" && typeof m.unsubscribe === "function" && typeof m.dispatch === "function", { searchExports: true }),
      () => BdApi.findModuleByProps && BdApi.findModuleByProps("subscribe", "unsubscribe", "dispatch"),
    ]);
    this.UserStore = this.find([
      () => W.getStore("UserStore"),
      () => W.Stores && W.Stores.UserStore,
      () => W.getModule((m) => m && typeof m.getCurrentUser === "function" && typeof m.getUser === "function", { searchExports: true }),
    ]);
    this.SelectedChannelStore = this.find([
      () => W.getStore("SelectedChannelStore"),
      () => W.Stores && W.Stores.SelectedChannelStore,
    ]);

    if (!this.Dispatcher || !this.UserStore) {
      if (attempt < 5) { this.retryTimer = setTimeout(() => this.connect(attempt + 1), 3000); return; }
      const falta = [!this.Dispatcher && "dispatcher", !this.UserStore && "usuarios"].filter(Boolean).join(" y ");
      BdApi.UI.showToast("MinecraftDiscord: no encontré " + falta + " de Discord. Los logros no van a andar (el arco y los clics sí).", { type: "error" });
      return;
    }
    this.handlers = {
      CONNECTION_OPEN: () => { this.connectedAt = Date.now(); },
      GUILD_CREATE: (e) => this.onGuildCreate(e),
      RELATIONSHIP_ADD: (e) => this.onRelationship(e),
      SPEAKING: (e) => this.onSpeaking(e),
      MESSAGE_CREATE: (e) => this.onMessage(e),
    };
    for (const [t, fn] of Object.entries(this.handlers)) this.Dispatcher.subscribe(t, fn);
  }

  stop() {
    this.stopped = true;
    clearTimeout(this.retryTimer);
    document.removeEventListener("click", this.onClick, true);
    document.removeEventListener("contextmenu", this.onContext, true);
    if (this.Dispatcher && this.handlers) for (const [t, fn] of Object.entries(this.handlers)) this.Dispatcher.unsubscribe(t, fn);
    this.handlers = null;
    BdApi.Patcher.unpatchAll(PLUGIN);
    if (this.container) this.container.remove();
    BdApi.DOM.removeStyle(PLUGIN);
    this.urls.forEach((u) => URL.revokeObjectURL(u));
    this.urls = []; this.sounds = {};
  }

  /* ======================= Sonidos ======================= */
  blobUrl(bytes, type) {
    const u = URL.createObjectURL(new Blob([bytes], { type }));
    this.urls.push(u);
    return u;
  }

  loadSounds() {
    this.urls.forEach((u) => URL.revokeObjectURL(u));
    this.urls = [];
    this.sounds = {}; KINDS.forEach((k) => (this.sounds[k] = []));
    try {
      if (fs.existsSync(this.folder)) {
        for (const file of fs.readdirSync(this.folder)) {
          const ext = path.extname(file).toLowerCase();
          const lower = file.toLowerCase();
          const kind = KINDS.find((k) => lower.startsWith(k)) || (lower.includes("click") ? "click" : null);
          if (!MIMES[ext] || !kind) continue;
          this.sounds[kind].push(this.blobUrl(fs.readFileSync(path.join(this.folder, file)), MIMES[ext]));
        }
      }
    } catch (err) { /* sigue con lo incrustado */ }
    const embed = (kind, b64) => {
      if (this.sounds[kind].length) return;
      const bin = atob(b64);
      this.sounds[kind].push(this.blobUrl(Uint8Array.from(bin, (c) => c.charCodeAt(0)), "audio/mpeg"));
    };
    embed("bow", BOW_B64);
    embed("click", CLICK_B64);
  }

  play(kinds, volume, pitch) {
    const list = [].concat(...[].concat(kinds).map((k) => this.sounds[k] || []));
    if (!list.length) return;
    const a = new Audio(list[Math.floor(Math.random() * list.length)]);
    a.volume = Math.min(1, Math.max(0, volume));
    if (pitch) { a.preservesPitch = false; a.playbackRate = 0.9 + Math.random() * 0.25; }
    a.play().catch(() => {});
  }

  /* ======================= Arco al recibir mensajes ======================= */
  isBowId(id) {
    const ids = ["message1", "message3"];
    if (this.settings.bowMentions) ids.push("message2", "mention1", "mention2", "mention3");
    return ids.includes(id);
  }

  fakeSound() {
    return new Proxy({}, { get: (_, prop) => (prop === "then" ? undefined : () => {}) });
  }

  setupBow() {
    try {
      const found = BdApi.Webpack.getWithKey(BdApi.Webpack.Filters.byStrings(".playWithListener().then"));
      const [mod, key] = found || [];
      if (mod && key) {
        BdApi.Patcher.instead(PLUGIN, mod, key, (thisObj, args, original) => {
          if (this.settings.bow && this.isBowId(args && args[0])) {
            this.play("bow", this.settings.bowVolume, false);
            return this.fakeSound();
          }
          return original.apply(thisObj, args);
        });
        this.bowMode = "directo";
        return;
      }
    } catch (err) { /* cae al modo manual */ }
    this.bowMode = "manual";
    BdApi.UI.showToast("MinecraftDiscord: modo manual para el arco. En Discord, apagá el sonido de mensajes (Notificaciones → Sonidos).", { type: "warning" });
  }

  manualBow(e) {
    const me = this.me, m = e && e.message;
    if (!this.settings.bow || this.bowMode !== "manual" || !me || !m || !m.author || m.author.id === me.id || e.optimistic) return;
    const sel = this.SelectedChannelStore && this.SelectedChannelStore.getChannelId && this.SelectedChannelStore.getChannelId();
    const mentioned = (m.mentions || []).some((u) => u.id === me.id) || m.mention_everyone;
    if (!m.guild_id || mentioned || e.channelId === sel) this.play("bow", this.settings.bowVolume, false);
  }

  /* ======================= Clics ======================= */
  isClickable(el) {
    return !!(el && el.closest && el.closest(
      'button, a, [role="button"], [role="tab"], [role="menuitem"], [role="option"], ' +
      '[role="switch"], [role="checkbox"], [role="radio"], [data-list-item-id], [class*="clickable"]'));
  }
  clickSound(right) {
    if (!this.settings.clicks) return;
    const now = Date.now();
    if (now - this.lastClick < 40) return;
    this.lastClick = now;
    const s = this.sounds;
    let kind = "click"; // click de botón de Minecraft (viene incrustado)
    if (this.settings.clickStyle === "bloque" && (s.place.length || s.break.length)) {
      kind = right ? (s.break.length ? "break" : "place") : (s.place.length ? "place" : "break");
    }
    this.play(kind, this.settings.clickVolume, this.settings.pitch);
  }
  onClick(e) { if (e.button === 0 && this.isClickable(e.target)) this.clickSound(false); }
  onContext() { if (this.settings.rightClick) this.clickSound(true); }

  /* ======================= Logros ======================= */
  onGuildCreate(e) {
    const g = e && e.guild;
    if (!g || !this.settings.server || this.seen.has("g" + g.id)) return;
    const joinedAt = g.joined_at ? Date.parse(g.joined_at) : 0;
    if (!joinedAt || Date.now() - joinedAt > 60000) return;
    this.seen.add("g" + g.id);
    const me = this.me, owner = g.owner_id || g.ownerId;
    if (me && owner === me.id) this.show("server", "Nuevo mundo");
    else this.show("joined", "Bienvenido al servidor");
  }
  onRelationship(e) {
    const rel = e && e.relationship;
    if (!rel || rel.type !== 1 || !this.settings.friend || !this.warmedUp || this.seen.has("f" + rel.id)) return;
    this.seen.add("f" + rel.id);
    setTimeout(() => this.seen.delete("f" + rel.id), 10000);
    const user = rel.user || (this.UserStore.getUser && this.UserStore.getUser(rel.id));
    const name = user ? (user.global_name || user.globalName || user.username) : "";
    this.show("friend", name ? "Nuevo amigo: " + name : "Nuevo amigo");
  }
  onSpeaking(e) {
    const me = this.me;
    if (!me || this.spoke || !this.settings.voice || !this.warmedUp) return;
    if (e && e.userId === me.id && e.speakingFlags > 0) { this.spoke = true; this.show("voice", "Voz del pueblo"); }
  }
  onMessage(e) {
    this.manualBow(e);
    const me = this.me, m = e && e.message;
    if (!me || this.messaged || !this.settings.message || !this.warmedUp) return;
    if (m && m.author && m.author.id === me.id) { this.messaged = true; this.show("message", "¡Hola, mundo!"); }
  }

  show(kind, name) {
    if (!this.container) return;
    const cfg = TOASTS[kind];
    const el = document.createElement("div");
    el.className = "mcl-toast" + (cfg.challenge ? " mcl-challenge" : "");
    el.style.setProperty("--mcl-dur", this.settings.duration + "s");
    const icon = document.createElement("div"); icon.className = "mcl-icon";
    const img = document.createElement("img"); img.src = cfg.icon(); icon.appendChild(img);
    const text = document.createElement("div"); text.className = "mcl-text";
    const t = document.createElement("div"); t.className = "mcl-title"; t.textContent = cfg.title;
    const n = document.createElement("div"); n.className = "mcl-name"; n.textContent = name;
    text.append(t, n);
    el.append(icon, text);
    el.addEventListener("animationend", () => el.remove());
    this.container.appendChild(el);
    if (this.settings.logroSound) this.play(cfg.challenge ? ["desafio", "logro"] : "logro", this.settings.logroVolume, false);
  }

  /* ======================= Ajustes ======================= */
  getSettingsPanel() {
    const panel = document.createElement("div");
    panel.style.cssText = "display:flex;flex-direction:column;gap:12px;color:var(--text-normal,#fff);padding:8px 0";
    const head = (t) => { const h = document.createElement("div"); h.textContent = t; h.style.cssText = "font-weight:700;margin-top:10px;font-size:15px"; return h; };
    const check = (label, key) => {
      const row = document.createElement("label"); row.style.cssText = "display:flex;align-items:center;gap:10px;cursor:pointer";
      const i = document.createElement("input"); i.type = "checkbox"; i.checked = this.settings[key];
      i.onchange = () => { this.settings[key] = i.checked; this.save(); };
      row.append(i, document.createTextNode(label)); return row;
    };
    const slider = (label, key, min, max, step, fmt) => {
      const row = document.createElement("label"); row.style.cssText = "display:flex;flex-direction:column;gap:6px";
      const txt = document.createElement("span");
      const i = document.createElement("input"); i.type = "range"; i.min = min; i.max = max; i.step = step; i.value = this.settings[key];
      const upd = () => (txt.textContent = label + ": " + fmt(this.settings[key]));
      i.oninput = () => { this.settings[key] = Number(i.value); upd(); this.save(); };
      upd(); row.append(txt, i); return row;
    };
    const select = (label, key, options) => {
      const row = document.createElement("label"); row.style.cssText = "display:flex;align-items:center;gap:10px";
      const sel = document.createElement("select");
      for (const [val, txt] of options) { const o = document.createElement("option"); o.value = val; o.textContent = txt; sel.appendChild(o); }
      sel.value = this.settings[key];
      sel.onchange = () => { this.settings[key] = sel.value; this.save(); };
      row.append(document.createTextNode(label), sel); return row;
    };
    const btn = (label, fn) => { const b = document.createElement("button"); b.textContent = label; b.style.cssText = "padding:6px 12px;cursor:pointer"; b.onclick = fn; return b; };
    const wrap = (...els) => { const d = document.createElement("div"); d.style.cssText = "display:flex;flex-wrap:wrap;gap:8px"; d.append(...els); return d; };
    const note = (t) => { const d = document.createElement("div"); d.style.cssText = "opacity:.7;font-size:13px"; d.textContent = t; return d; };

    panel.append(
      head("🏹 Arco al recibir mensajes"),
      check("Reemplazar el sonido de mensaje por el arco", "bow"),
      check("También en menciones", "bowMentions"),
      slider("Volumen del arco", "bowVolume", 0, 1, 0.05, (v) => Math.round(v * 100) + "%"),
      wrap(btn("Probar arco", () => this.play("bow", this.settings.bowVolume, false))),
      note("Modo actual: " + this.bowMode + (this.bowMode === "manual" ? " (apagá el sonido de mensajes de Discord para que no suene doble)" : "")),

      head("🧱 Sonidos al hacer clic"),
      check("Sonido al hacer clic", "clicks"),
      select("Estilo:", "clickStyle", [["boton", "Click de botón de Minecraft"], ["bloque", "Colocar/romper bloque (necesita los archivos place*/break*)"]]),
      check("También con clic derecho", "rightClick"),
      check("Variar el tono al azar", "pitch"),
      slider("Volumen de clics", "clickVolume", 0, 1, 0.05, (v) => Math.round(v * 100) + "%"),
      wrap(btn("Probar clic", () => this.play("click", this.settings.clickVolume, this.settings.pitch))),

      head("🏆 Logros"),
      check("Al crear o unirte a un servidor", "server"),
      check("Al agregar un amigo", "friend"),
      check("La primera vez que hablás por voz", "voice"),
      check("Con tu primer mensaje de la sesión", "message"),
      check("Sonido del logro (si hay archivo logro*.ogg)", "logroSound"),
      slider("Duración del cartel", "duration", 3, 10, 1, (v) => v + " s"),
      slider("Volumen del logro", "logroVolume", 0, 1, 0.05, (v) => Math.round(v * 100) + "%"),
      wrap(
        btn("Probar: servidor", () => this.show("server", "Nuevo mundo")),
        btn("Probar: amigo", () => this.show("friend", "Nuevo amigo: Steve")),
        btn("Probar: voz", () => this.show("voice", "Voz del pueblo")),
        btn("Probar: mensaje", () => this.show("message", "¡Hola, mundo!"))
      ),

      head("📁 Sonidos"),
      wrap(btn("Recargar sonidos", () => { this.loadSounds(); BdApi.UI.showToast("Sonidos recargados", { type: "success" }); })),
      note("Carpeta: " + this.folder + " (click*.mp3, place*.ogg, break*.ogg, logro*.ogg, desafio*.ogg, bow*.mp3)")
    );
    return panel;
  }
};
